FROM node:alpine

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./

RUN npm install \
&& npm cache clean --force

# WORKDIR /app/src

COPY . .
# COPY ./.next ./.next
# COPY ./public ./public
# COPY ./css ./css
# COPY ./next.config.js ./next.config.js

RUN npm run build

EXPOSE 3000

CMD ["npm","run","start"]
