FROM node:alpine
ENV NODE_ENV=development 
WORKDIR /app
COPY package*.json ./
RUN npm install \
	&& npm cache clean --force
WORKDIR /app/src
COPY . .
RUN cp _document.js .next/server/pages/_document.js 
EXPOSE 3000
CMD ["npm","run","dev"]
