version: "2.4"
services: 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - "80:80"
      #- "3050:80"
    depends_on:
    - client
    networks:
    - app-network

  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - ./client:/app/src
    ports:
    - "3000:3000"
    depends_on:
    - api                    
    networks:
    - app-network

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
    - ./api:/opt/app
    ports:
    - "5000:5000"
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    networks:
    - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
    networks:
    - app-network

networks:
  app-network:
    driver: bridge
