version: "3.9"

services: 
  nginx:
    restart: always
    image: djedjethai/tprnginx:latest
    ports:
    - "80:80"
    - "443:443"
    networks:
    - mynet

  client:
    restart: always
    image: djedjethai/tprclient:latest
    volumes:
    - ./client:/app/src
    ports:
    - "3000:3000"
    networks:
    - mynet

  api:
    image: djedjethai/tprapi:latest
    volumes:
    - ./api:/opt/app
    ports:
    - "5000:5000"
    environment:
      ACCESS_KEY_ID: /run/secrets/access-key-id
      SECRET_ACCESS_KEY: /run/secrets/secret-access-key
      BUCKET_NAME: /run/secrets/bucket-name
      SESSION_SECRET: /run/secrets/session-secret
      MONGO_URI: /run/secrets/mongo-uri
      PASSWORD_ADMIN: /run/secrets/password-admin
      ADMIN: /run/secrets/admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    secrets:
    - access-key-id
    - secret-access-key
    - bucket-name
    - session-secret
    - mongo-uri
    - password-admin
    - admin 
    networks:
    - mynet

  redis:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
    networks:
    - mynet

networks:
  mynet:

secrets:
  access-key-id:
    external: true
  secret-access-key:
    external: true
  bucket-name:
    external: true
  session-secret:
    external: true
  mongo-uri:
    external: true
  password-admin:
    external: true
  admin:
    external: true
