version: "2.4"
services: 
        nginx:
                restart: always
                build:
                        dockerfile: Dockerfile.dev
                        context: ./nginx
                ports:
                        - "3050:80"
                depends_on:
                        - client
        client:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./client
                volumes:
                        - ./client:/opt/app
                ports:
                        - "3000:3000"
        api:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./api
                volumes:
                        - ./api:/opt/app
                ports:
                        - "5000:5000"


